### ISSUE TITLE
Not working with SSR on sveltekit

### ISSUE THREAD

**Issue by ceifa** [denisstasyev/svelte-skeleton#2]
When I try to use it out of the box on sveltekit it just throws an error.
I had to add an check if user is being rendered by the browser. Is this how it is supposed to be?

**Comment by denisstasyev** [comment]
Thank you for report, I use this package with pure Svelte and have no problems. Maybe you can create a REPL or describe the steps to reproduce?

**Comment by denisstasyev** [comment]
There may be a problem with the publication format.  Is there a problem if you just copy the component as it is into your project?

If the problem persists, please let me know.  I'll try on the weekend to look at a bunch with Svelte Kit

**Comment by ceifa** [comment]
> There may be a problem with the publication format. Is there a problem if you just copy the component as it is into your project?

No, it works fine! I will do that, thanks.

**Comment by denisstasyev** [comment]
@ceifa Changed publishing format, now you can try to import `.svelte` file as described in README.md
